"""OAuth 2.1 provider for the Windows Login Monitor MCP server.

Implements the MCP 2025-06-18 Authorization spec:
- RFC 7591 Dynamic Client Registration  (any client can self-register)
- RFC 9728 Protected-Resource Metadata (FastMCP serves this automatically)
- PKCE (S256) on the authorization-code flow
- RFC 7009 token revocation

This is a single-owner provider — only the person who knows the *owner key*
(WLM_MCP_OWNER_KEY, generated by the installer) can complete an authorization.
Once authorized, the OAuth client (Claude.ai, Claude Code, etc.) gets its own
opaque access + refresh tokens that we issue and validate locally.

Persistence:
  - Registered clients persist to JSON next to the server (so re-adding the
    connector after a server restart Just Works).
  - Authorization codes, access tokens, and refresh tokens live in memory.
    A restart invalidates them; the client refreshes silently via DCR + the
    next /authorize round-trip.
"""

from __future__ import annotations

import json
import os
import secrets
import time
from pathlib import Path
from typing import Optional
from urllib.parse import urlencode

from mcp.server.auth.provider import (
    AccessToken,
    AuthorizationCode,
    AuthorizationParams,
    OAuthAuthorizationServerProvider,
    RefreshToken,
)
from mcp.shared.auth import OAuthClientInformationFull, OAuthToken

# Defaults; the server module can override at construction time.
ACCESS_TOKEN_TTL = 60 * 60          # 1 hour
REFRESH_TOKEN_TTL = 60 * 60 * 24 * 30  # 30 days
AUTH_CODE_TTL = 60                  # 1 minute


def _now() -> int:
    return int(time.time())


def _random(n: int = 32) -> str:
    """URL-safe random secret."""
    return secrets.token_urlsafe(n)


class SimpleOAuthProvider(
    OAuthAuthorizationServerProvider[AuthorizationCode, RefreshToken, AccessToken]
):
    """OAuth provider gated by a single shared owner key.

    The owner key authenticates the *human* at the /authorize step. After
    that, the OAuth client gets its own tokens.
    """

    def __init__(self, owner_key: str, state_file: Path):
        if not owner_key:
            raise ValueError("owner_key cannot be empty")
        self.owner_key = owner_key
        self.state_file = state_file

        # In-memory stores (codes / tokens — short-lived, fine to lose on restart)
        self._codes: dict[str, AuthorizationCode] = {}
        self._access: dict[str, AccessToken] = {}
        self._refresh: dict[str, RefreshToken] = {}

        # Clients persist to JSON so reconnects after a restart skip DCR
        self._clients: dict[str, OAuthClientInformationFull] = {}
        self._load_clients()

    # ---------------- persistence ----------------

    def _load_clients(self) -> None:
        if not self.state_file.exists():
            return
        try:
            data = json.loads(self.state_file.read_text(encoding="utf-8"))
            for cid, blob in data.get("clients", {}).items():
                self._clients[cid] = OAuthClientInformationFull.model_validate(blob)
        except Exception as e:  # corrupt state shouldn't crash the server
            print(f"[oauth] WARN: ignoring corrupt {self.state_file}: {e}", flush=True)

    def _save_clients(self) -> None:
        data = {"clients": {c.client_id: c.model_dump(mode="json") for c in self._clients.values()}}
        tmp = self.state_file.with_suffix(".tmp")
        tmp.write_text(json.dumps(data, indent=2), encoding="utf-8")
        tmp.replace(self.state_file)

    # ---------------- client registration ----------------

    async def register_client(self, client_info: OAuthClientInformationFull) -> None:
        # The handler sets client_id + secret before calling us; just persist.
        self._clients[client_info.client_id] = client_info
        self._save_clients()

    async def get_client(self, client_id: str) -> OAuthClientInformationFull | None:
        return self._clients.get(client_id)

    # ---------------- authorization ----------------

    async def authorize(
        self,
        client: OAuthClientInformationFull,
        params: AuthorizationParams,
    ) -> str:
        """Called from the owner-key-gated handler. Issues a code + builds the
        redirect URL back to the client."""
        code = _random(24)
        self._codes[code] = AuthorizationCode(
            code=code,
            scopes=params.scopes or ["mcp"],
            expires_at=time.time() + AUTH_CODE_TTL,
            client_id=client.client_id,
            code_challenge=params.code_challenge,
            redirect_uri=params.redirect_uri,
            redirect_uri_provided_explicitly=params.redirect_uri_provided_explicitly,
            resource=params.resource,
        )
        q = {"code": code}
        if params.state:
            q["state"] = params.state
        sep = "&" if "?" in str(params.redirect_uri) else "?"
        return f"{params.redirect_uri}{sep}{urlencode(q)}"

    async def load_authorization_code(
        self, client: OAuthClientInformationFull, authorization_code: str
    ) -> AuthorizationCode | None:
        ac = self._codes.get(authorization_code)
        if ac is None or ac.client_id != client.client_id:
            return None
        if ac.expires_at < time.time():
            self._codes.pop(authorization_code, None)
            return None
        return ac

    async def exchange_authorization_code(
        self,
        client: OAuthClientInformationFull,
        authorization_code: AuthorizationCode,
    ) -> OAuthToken:
        # PKCE verification is handled by the handler before reaching us.
        self._codes.pop(authorization_code.code, None)

        access = _random(32)
        refresh = _random(32)
        now = _now()
        self._access[access] = AccessToken(
            token=access,
            client_id=client.client_id,
            scopes=authorization_code.scopes,
            expires_at=now + ACCESS_TOKEN_TTL,
            resource=authorization_code.resource,
        )
        self._refresh[refresh] = RefreshToken(
            token=refresh,
            client_id=client.client_id,
            scopes=authorization_code.scopes,
            expires_at=now + REFRESH_TOKEN_TTL,
        )
        return OAuthToken(
            access_token=access,
            token_type="Bearer",
            expires_in=ACCESS_TOKEN_TTL,
            refresh_token=refresh,
            scope=" ".join(authorization_code.scopes),
        )

    # ---------------- refresh ----------------

    async def load_refresh_token(
        self, client: OAuthClientInformationFull, refresh_token: str
    ) -> RefreshToken | None:
        rt = self._refresh.get(refresh_token)
        if rt is None or rt.client_id != client.client_id:
            return None
        if rt.expires_at is not None and rt.expires_at < _now():
            self._refresh.pop(refresh_token, None)
            return None
        return rt

    async def exchange_refresh_token(
        self,
        client: OAuthClientInformationFull,
        refresh_token: RefreshToken,
        scopes: list[str],
    ) -> OAuthToken:
        # Rotate both tokens.
        self._refresh.pop(refresh_token.token, None)
        new_scopes = scopes or refresh_token.scopes

        access = _random(32)
        new_refresh = _random(32)
        now = _now()
        self._access[access] = AccessToken(
            token=access,
            client_id=client.client_id,
            scopes=new_scopes,
            expires_at=now + ACCESS_TOKEN_TTL,
            resource=None,
        )
        self._refresh[new_refresh] = RefreshToken(
            token=new_refresh,
            client_id=client.client_id,
            scopes=new_scopes,
            expires_at=now + REFRESH_TOKEN_TTL,
        )
        return OAuthToken(
            access_token=access,
            token_type="Bearer",
            expires_in=ACCESS_TOKEN_TTL,
            refresh_token=new_refresh,
            scope=" ".join(new_scopes),
        )

    # ---------------- access-token verification ----------------

    async def load_access_token(self, token: str) -> AccessToken | None:
        at = self._access.get(token)
        if at is None:
            return None
        if at.expires_at is not None and at.expires_at < _now():
            self._access.pop(token, None)
            return None
        return at

    # ---------------- revocation ----------------

    async def revoke_token(self, token):  # AccessToken | RefreshToken
        # `token` is a model instance here, not a raw string.
        tk = getattr(token, "token", None)
        if tk:
            self._access.pop(tk, None)
            self._refresh.pop(tk, None)
